In [2]:
import numpy as np

In [3]:
x =[1,2,3,4,5]
y = np.array(x)
print(y)
print(type(y))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
x =  np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
# 3dimensional array
x= np.array(
    [
                [
                    [1,2,3],[4,5,6],[7,8,9]
                ],
                [
                    [7,8,9],[10,11,12],[4,5,6]
                ]
            ]
    )

print(x)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 7  8  9]
  [10 11 12]
  [ 4  5  6]]]


In [23]:
print(x[1,1,1])

print(x[1,1])

print(x[1])

print(x[1,0,1])

print(x[0,0:,1:3])

11
[10 11 12]
[[ 7  8  9]
 [10 11 12]
 [ 4  5  6]]
8
[[2 3]
 [5 6]
 [8 9]]
